/**
 * Emergency Shutdown Codegen Script
 *
 * Fetches emergency-config.json and emergency-abis.json from the olympus-v3 repo
 * and generates TypeScript files for the frontend.
 *
 * Usage: pnpm codegen:emergency
 */

import fs from "node:fs";
import path from "node:path";

// todo: change CallistoDAO to OlympusDAO when PR(https://github.com/OlympusDAO/olympus-v3/pull/198) will merge
const BASE_URL =
  "https://raw.githubusercontent.com/CallistoDAO/olympus-v3/emergency/documentation/emergency";

const OUTPUT_DIR = path.resolve("src/generated/emergency");

// ── Fetch helpers ──────────────────────────────────────────────────────────

async function fetchJSON<T>(url: string): Promise<T> {
  console.log(`Fetching ${url}...`);
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Failed to fetch ${url}: ${res.status}`);
  return res.json() as Promise<T>;
}

// ── Types for the config ───────────────────────────────────────────────────

interface CallArg {
  name: string;
  type: string;
  value: unknown;
  envKey?: string;
}

interface EmergencyCallConfig {
  abi: string;
  args: CallArg[];
  contractKey: string;
  function: string;
  signature: string;
}

interface EmergencyComponentConfig {
  id: string;
  name: string;
  description: string;
  category: string;
  severity: string;
  owner: string;
  availableOn: string[];
  calls: EmergencyCallConfig[];
  batchScript?: string;
  dependencies?: string[];
  shutdownCriteria: string[];
  postShutdownSteps: string[];
}

interface ChainConfig {
  chainId: number;
  contracts: Record<string, string>;
  multisigs: Record<string, string>;
}

interface EmergencyConfig {
  version: string;
  chains: Record<string, ChainConfig>;
  components: EmergencyComponentConfig[];
  contractRegistry: string[];
}

type AbiMap = Record<string, unknown[]>;

// ── Generators ─────────────────────────────────────────────────────────────

function generateTypes(): string {
  return `// Auto-generated by scripts/emergency-codegen.ts — DO NOT EDIT

export type ChainId = 1 | 10 | 42161 | 8453 | 80094 | 11155111;

export type ChainName = "mainnet" | "optimism" | "arbitrum" | "base" | "berachain" | "sepolia";

export type MultisigOwner = "emergency" | "dao";

export type ComponentCategory = "treasury" | "lending" | "core" | "emissions" | "bridge" | "reserve";

export type Severity = "critical" | "high" | "medium" | "low";

export interface EmergencyCallArg {
  readonly name: string;
  readonly type: string;
  readonly value: unknown;
  readonly envKey?: string;
}

export interface EmergencyCall {
  readonly abi: string;
  readonly args: readonly EmergencyCallArg[];
  readonly contractKey: string;
  readonly function: string;
  readonly signature: string;
}

export interface EmergencyComponent {
  readonly id: string;
  readonly name: string;
  readonly description: string;
  readonly category: ComponentCategory;
  readonly severity: Severity;
  readonly owner: MultisigOwner;
  readonly availableOn: readonly ChainName[];
  readonly calls: readonly EmergencyCall[];
  readonly batchScript?: string;
  readonly dependencies?: readonly string[];
  readonly shutdownCriteria: readonly string[];
  readonly postShutdownSteps: readonly string[];
}

export interface ChainAddresses {
  readonly chainId: ChainId;
  readonly contracts: Readonly<Record<string, \`0x\${string}\`>>;
  readonly multisigs: Readonly<Partial<Record<MultisigOwner, \`0x\${string}\`>>>;
}
`;
}

function generateComponents(config: EmergencyConfig): string {
  const components = config.components.map((c) => ({
    id: c.id,
    name: c.name,
    description: c.description,
    category: c.category,
    severity: c.severity,
    owner: c.owner,
    availableOn: c.availableOn,
    calls: c.calls.map((call) => ({
      abi: call.abi,
      args: call.args,
      contractKey: call.contractKey,
      function: call.function,
      signature: call.signature,
    })),
    batchScript: c.batchScript,
    dependencies: c.dependencies,
    shutdownCriteria: c.shutdownCriteria,
    postShutdownSteps: c.postShutdownSteps,
  }));

  return `// Auto-generated by scripts/emergency-codegen.ts — DO NOT EDIT

import type { EmergencyComponent } from "./types.ts";

export const EMERGENCY_COMPONENTS: readonly EmergencyComponent[] = ${JSON.stringify(components, null, 2)} as const;
`;
}

function generateAddresses(config: EmergencyConfig): string {
  const chainIdToName: Record<number, string> = {};
  const chainNameToId: Record<string, number> = {};
  const addresses: Record<string, unknown> = {};

  for (const [chainName, chain] of Object.entries(config.chains)) {
    chainIdToName[chain.chainId] = chainName;
    chainNameToId[chainName] = chain.chainId;
    addresses[chain.chainId] = {
      chainId: chain.chainId,
      contracts: chain.contracts,
      multisigs: chain.multisigs,
    };
  }

  return `// Auto-generated by scripts/emergency-codegen.ts — DO NOT EDIT

import type { ChainId, ChainName, ChainAddresses } from "./types.ts";

export const CHAIN_ID_TO_NAME: Readonly<Record<ChainId, ChainName>> = ${JSON.stringify(chainIdToName, null, 2)} as Record<ChainId, ChainName>;

export const CHAIN_NAME_TO_ID: Readonly<Record<ChainName, ChainId>> = ${JSON.stringify(chainNameToId, null, 2)} as Record<ChainName, ChainId>;

export const EMERGENCY_ADDRESSES: Readonly<Record<ChainId, ChainAddresses>> = ${JSON.stringify(addresses, null, 2)} as Record<ChainId, ChainAddresses>;
`;
}

function generateAbiFile(abiKey: string, abi: unknown[]): string {
  return `${JSON.stringify(abi, null, 2)}\n`;
}

function toCamelCase(str: string): string {
  return str.replace(/_([a-z])/g, (_, c: string) => c.toUpperCase());
}

function generateIndex(abiKeys: string[]): string {
  const abiImports = abiKeys
    .map((key) => {
      const camel = toCamelCase(key);
      return `import ${camel}AbiJson from "./abis/${key}.json" with { type: "json" };`;
    })
    .join("\n");

  const abiExports = abiKeys
    .map((key) => {
      const camel = toCamelCase(key);
      return `export const ${camel}Abi = ${camel}AbiJson;`;
    })
    .join("\n");

  return `// Auto-generated by scripts/emergency-codegen.ts — DO NOT EDIT

export * from "./types.ts";
export * from "./components.ts";
export * from "./addresses.ts";

${abiImports}

${abiExports}
`;
}

// ── Main ───────────────────────────────────────────────────────────────────

async function main() {
  console.log("Emergency Codegen: Starting...\n");

  const [config, abis] = await Promise.all([
    fetchJSON<EmergencyConfig>(`${BASE_URL}/emergency-config.json`),
    fetchJSON<AbiMap>(`${BASE_URL}/emergency-abis.json`),
  ]);

  // Clean & create output dirs
  if (fs.existsSync(OUTPUT_DIR)) {
    fs.rmSync(OUTPUT_DIR, { recursive: true });
  }
  fs.mkdirSync(path.join(OUTPUT_DIR, "abis"), { recursive: true });

  // Generate types.ts
  fs.writeFileSync(path.join(OUTPUT_DIR, "types.ts"), generateTypes());
  console.log("  ✓ types.ts");

  // Generate components.ts
  fs.writeFileSync(
    path.join(OUTPUT_DIR, "components.ts"),
    generateComponents(config)
  );
  console.log(
    `  ✓ components.ts (${config.components.length} components)`
  );

  // Generate addresses.ts
  fs.writeFileSync(
    path.join(OUTPUT_DIR, "addresses.ts"),
    generateAddresses(config)
  );
  console.log(
    `  ✓ addresses.ts (${Object.keys(config.chains).length} chains)`
  );

  // Generate ABI files
  const abiKeys = Object.keys(abis).filter((k) => !k.startsWith("$"));
  for (const key of abiKeys) {
    fs.writeFileSync(
      path.join(OUTPUT_DIR, "abis", `${key}.json`),
      generateAbiFile(key, abis[key])
    );
  }
  console.log(`  ✓ abis/ (${abiKeys.length} files)`);

  // Generate index.ts
  fs.writeFileSync(path.join(OUTPUT_DIR, "index.ts"), generateIndex(abiKeys));
  console.log("  ✓ index.ts");

  console.log(`\nDone! Files written to ${OUTPUT_DIR}`);
}

main().catch((err) => {
  console.error("Codegen failed:", err);
  process.exit(1);
});
